AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Roles for OpenSearch and SageMaker

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EC2Permissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - cloudwatch:PutMetricData
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: EC2Role

  OpenSearchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - opensearchservice.amazonaws.com
                - sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: OpenSearchPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:::log-group:/aws/aes/domains/*'

Outputs:
  EC2RoleArn:
    Description: "ARN of the EC2 Role"
    Value: !GetAtt EC2Role.Arn

  EC2InstanceProfileArn:
    Description: "ARN of the EC2 Instance Profile"
    Value: !GetAtt EC2InstanceProfile.Arn

  OpenSearchServiceRoleArn:
    Description: "ARN of the OpenSearch Service Role"
    Value: !GetAtt OpenSearchServiceRole.Arn

